### ISSUE TITLE
Problem with jellyfish step

### ISSUE THREAD

**Issue by dekhost** [marbl/MHAP#8]
Hello!
I'm using MHAP as part of the PBcR pipeline, so I'm not sure if this is the place to ask, but thought I'd try anyway. I'm testing a range of parameters for MHAP and certain combos seem to fail early on during the jellyfish step, while others pass through it just fine. Here is a typical output:

Running with 40.0000115076923X (for genome size 130000000) of dmel_pacbio sequences (5200001496 bp).
Correcting with 121X sequences (15743312583 bp).
----------------------------------------START Fri Jul 17 21:34:36 2015
/gpfs/fs1/sfw/wgs/8.3/Linux-amd64/bin/jellyfish count  -m 10 -s 120000000 -t 24 -o /scratch/dkhost/lab_shared/dmel_MHAP_array/1_10_1000.params//tempdmel_pacbio/asm.mers /scratch/dkhost/bergman_pacbio_reads/pacbio_reads_vs_celera25X_filtered+BLASR/data/filtered_subreads.fastq
Failed to open input file '/scratch/dkhost/lab_shared/dmel_MHAP_array/1_10_1000.params//tempdmel_pacbio/asm.mers1021'
----------------------------------------END Sun Jul 19 04:37:28 2015 (111772 seconds)
Failed to execute /gpfs/fs1/sfw/wgs/8.3/Linux-amd64/bin/jellyfish count  -m 10 -s 120000000 -t 24 -o /scratch/dkhost/lab_shared/dmel_MHAP_array/1_10_1000.params//tempdmel_pacbio/asm.mers /scratch/dkhost/bergman_pacbio_reads/pacbio_reads_vs_celera25X_filtered+BLASR/data/filtered_subreads.fastq

As far as I can tell, that file does exist, and again other combos run ok. It seems to be a problem with small kmers or much larger kmers, perhaps it is a memory issue? This run had kmer=10, and sketch size=1000, I can give you the whole spec file if needed. Any suggestions you have would be greatly appreciated!
Best,
Emerson

**Comment by skoren** [comment]
Hi,

Yes memory is a likely issue. You can try running the jellyfish command that is failing by hand to see what the full error it reports is and help diagnose what is going wrong. The file is optional and you could create a blank one named asm.<kmer size>.ignore which will be picked up by the pipeline and used instead of generating counts with jellyfish as a workaround.

That said, I would advise against using a k-mer below 14 or 12 because there will be many repetitive hits in the genome. Going much larger than 16 would significantly reduce your chance of finding a hit due to the high error rate in the PacBio sequences.
